### ISSUE TITLE
Peer to Peer Code Review #92team

### ISSUE THREAD

**Issue by rootDEV2990** [ezeilo-su/the-next-web-clone#1]
Awesome!!! Good job reusing sections and elements really cool. Responsive is coming along real well too!

Might also want to try...

-If CSS is too long relocate media queries to own css file. 
-Empty comments in html maybe aren't necessary. 
-Maybe fixed heights is not needed to help aid in responsive. 
-Stickler might notice the missing 0s and spaces in rgba #384.
-Try maybe rem or % for responsive aid. 

Keep it up!!

-

**Comment by flpfar** [comment]
Everything fixed, guys! Thank you for the tips :+1:
